### ISSUE TITLE
Warning: file_get_contents(/boot/config/plugins/rclone/.rclone.conf): failed to open stream: No such file or directory in /usr/local/emhttp/plugins/dynamix/include/DefaultPageLayout.php(528) : eval()'d code on line 30

### ISSUE THREAD

**Issue by bolavefasfas** [Waseh/rclone-unraid#18]
I was not able to install rclone this is the error please my I know what's this errors fix ??
![image](https://user-images.githubusercontent.com/82230241/188221438-b0734897-1a70-4adb-b88b-f14e0ee6a1e6.png)

**Comment by Waseh** [comment]
This error happens when the plugin didn't install the rclone binary for some reason.
To be honest i thought i had fixed this edge case by making sure the install failed with an error instead but that doesn't seem to be the case.

Most likely you are blocking the download from the rclone website somewhere (firewall, pihole)

The support thread for the plugin on the unraid forum has more information.

**Comment by Waseh** [comment]
Should be fixed in new release. By that i mean you should get a graceful fail when trying to install instead of this which gives the impression the install in fact happened.
#
